# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'Azure-sonar'
    scannerMode: 'Other'
    extraProperties: |
      mvn sonar:sonar \
        -Dsonar.projectKey=sonartest \
        -Dsonar.host.url=http://40.71.198.190:9000 \
        -Dsonar.login=1b1c3eea0af2a9026322be92bac079df3c1bbd1c
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'